version: "3.8"

services:
  #devcontainer용 컨테이너
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev-container
    volumes:
      - .:/workspace
    environment:
      - ENV:development
    depends_on:
      - service-entry
    command: sleep infinity

  #서비스별 컨테이너
  #service orchestration을 위한 service-entry 컨테이너
  service-entry:
    build:
      context: ./services/service-entry
      dockerfile: Dockerfile
    container_name: service-entry
    volumes:
      - ./services/service-entry/source:/app/source/service-entry
    ports:
      - "8000:8000"
    environment:
      - ENV:development
    depends_on:
      - document-generation-service
      - sharepoint-service
    command: sleep infinity

  #template service
  document-generation-service:
    build:
      context: ./services/document-generation-service
      dockerfile: Dockerfile
    container_name: document-generation-service
    volumes:
       - ./services/document-generation-service/source:/app/source/document-generation-service
    ports:
      - "8001:8001"
    environment:
      - ENV:development
    command: sleep infinity

  #sharepoint에 파일 저장 요청을 구성하기 위한 서비스
  sharepoint-service:
    build:
      context: ./services/sharepoint-service
      dockerfile: Dockerfile
    container_name: sharepoint-service
    volumes:
       - ./services/sharepoint-service/source:/app/source/sharepoint-service
    ports:
      - "8002:8002"
    environment:
      - ENV:development
    command: sleep infinity