version: "3.8"

services:
  #devcontainer용 컨테이너
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev-container
    volumes:
      - .:/workspace
    environment:
      - ENV=development
      - JIRA_BASE_URL=https://msimul.atlassian.net
      - JIRA_USERNAME=juwon@msimul.com
      - JIRA_API_TOKEN=ATATT3xFfGF06CSBKdkFDyj5YLGYHirFjoglCVtvLCia7XxTR57nYY-wj1rxkTVsa3Gpgd7fZ4pqcKIPdR7g9RJR9lpmkDXZA1D1eWKb-EceAayOpapM-wBn3NCg6KifTFEJqo5DsYGdMOFYl0Kg9j1TF0B1EFwA-VRZcGB0UFd94Cp03lO7IzE=68E2873A
      - JIRA_DOWNLOAD_DIR=/tmp/jira_attachments
    depends_on:
      - app
    command: sleep infinity


  db:
    image: postgres:14
    container_name: my-postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
     
    ports:
      - "5432:5432"
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: my-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - JIRA_BASE_URL=https://msimul.atlassian.net
      - JIRA_USERNAME=juwon@msimul.com
      - JIRA_API_TOKEN=ATATT3xFfGF06CSBKdkFDyj5YLGYHirFjoglCVtvLCia7XxTR57nYY-wj1rxkTVsa3Gpgd7fZ4pqcKIPdR7g9RJR9lpmkDXZA1D1eWKb-EceAayOpapM-wBn3NCg6KifTFEJqo5DsYGdMOFYl0Kg9j1TF0B1EFwA-VRZcGB0UFd94Cp03lO7IzE=68E2873A
      - JIRA_DOWNLOAD_DIR=/tmp/jira_attachments
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    volumes:
      - ./app:/workspace/app
      - ./output:/workspace/output
volumes:
  dbdata: {}    
