domain_config:
  company:
    query_key: name
    id_field: company_id
  employee:
    query_key: jira_account_id  
    id_field: accountId
  research:
    query_key: code
    id_field: research_id
  expert:
    query_key: id
    id_field: expert_id
  

field_patterns:
  # Company ID 필드 패턴
  company_id:
    type: company
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone
  supplier_id:
    type: company
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone
  customer_id:
    type: company
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone'
  사업자_선택:
    type: company
    value_key: value
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone

  # Employee ID 필드 패턴
  creator:
    type: employee
    id_field: accountId
    value_key: accountId
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
      - name: affiliation
      - name: phone
      - name: signature
      - name: stamp
      - name: bank_name
      - name: account_number
      - name: birth_date
  assignee:
    type: employee
    id_field: accountId
    value_key: accountId
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
      - name: affiliation
      - name: phone
      - name: signature
      - name: stamp
      - name: bank_name
      - name: account_number
      - name: birth_date
    
  

  # Research ID 필드 패턴
  project_id:
    type: research
    enrich_fields:
      - name: name
      - name: code
      - name: description
  연구과제_선택_key:
    type: research
    enrich_fields:
      - name: project_name
      - name: project_code
      - name: project_period
      - name: project_manager
      - name: status
      - name: description
      - name: project_start_date
      - name: project_end_date
      - name: budget

  # Expert ID 필드 패턴
  expert_id:
    type: expert
    enrich_fields:
      - name: name
      - name: expertise
      - name: organization
      - name: contact

  # 리스트 타입 필드 패턴
  employee_list:
    type: employee
    is_list: true
    id_field: accountId
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
      - name: affiliation
      - name: phone
      - name: signature
      - name: stamp
      - name: bank_name
      - name: account_number
      - name: birth_date

  내부_인원:
    type: employee
    is_list: true
    id_field: accountId
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
      - name: affiliation
      - name: phone
      - name: signature
      - name: stamp
      - name: bank_name
      - name: account_number
      - name: birth_date
  
  출장_참석자:
    type: employee
    is_list: true
    id_field: accountId
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
      - name: affiliation
      - name: phone
      - name: signature
      - name: stamp
      - name: bank_name
      - name: account_number
      - name: birth_date
  