domain_config:
  company:
    query_key: name
    id_field: company_id
  employee:
    query_key: account_id
    id_field: employee_id
  research:
    query_key: code
    id_field: research_id
  expert:
    query_key: id
    id_field: expert_id

field_patterns:
  # Company ID 필드 패턴
  company_id:
    type: company
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone
  supplier_id:
    type: company
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone
  customer_id:
    type: company
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone
  사업자_선택:
    type: company
    value_key: value
    enrich_fields:
      - name: company_name
      - name: address
      - name: rep_name
      - name: phone

  # Employee ID 필드 패턴
  employee_id:
    type: employee
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
  applicant_id:
    type: employee
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
  writer_id:
    type: employee
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
  manager_id:
    type: employee
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email

  # Research ID 필드 패턴
  project_id:
    type: research
    enrich_fields:
      - name: name
      - name: code
      - name: description
  research_id:
    type: research
    enrich_fields:
      - name: name
      - name: code
      - name: description

  # Expert ID 필드 패턴
  expert_id:
    type: expert
    enrich_fields:
      - name: name
      - name: expertise
      - name: organization
      - name: contact

  # 리스트 타입 필드 패턴
  employee_list:
    type: employee
    is_list: true
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email

participant_lists:
  internal_participants_data:
    type: employee
    id_field: employee_id
    enrich_fields:
      - name: name
      - name: department
      - name: position
      - name: email
  external_participants_data:
    type: company
    id_field: company_id
    enrich_fields:
      - name: name
      - name: address
      - name: representative
      - name: phone 